name: shearwater
channels:
- conda-forge
- defaults
dependencies:
- pip
- python>=3.8,<3.12
- pywps>=4.5.1,<4.7
- jinja2
- click
- psutil
- intake
- intake-esm
- pydantic<2
- requests
- aiohttp
# tests
- pytest
- pandoc
